export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '01/22/2025',
    '01/22/2025',
    '01/19/2025',
    '01/19/2025',
    '01/19/2025',
    '01/18/2025',
    '01/14/2025',
    '01/13/2025',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Abdelhak Assahsah',
    'Oumayma Hammouti',
    'Ilias Riyani',
    'Galina Van bokhorst',
    'Imane Azzaiani',
    'Oumayma Azouagh',
    'Romayssae Assahsah',
    'Khadija El maazouzi',
    'Dina Chadli',
    'Haytham El bejaoui',
    'Ouissame Arrasi',
    'Loubna Dallouzi',
    'Miranda Vink',
    'Aabir El boujdaini',
    'Yannick Jonker',
    'Aicha Harboul',
    'Salma Safir',
    'Omar Riyani',
    'Nouhayla Al marese',
    'Mariam Sadraoui',
    'Ikram El morsli',
    'Oumayma El mcabni',
    'Ouiam El bakkali',
    'Chaida Boulaich',
    'Hossam Kallah',
    'Sana Ahafraoui',
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    'Abdelhak@muntmasters.com',
    'Oumayma@muntmasters.com',
    'Ilias@muntmasters.com',
    'Firdous@muntmasters.com',
    'Galina@muntmasters.com',
    'Imane@muntmasters.com',
    'Souad@muntmasters.com',
    'Oumayma@muntmasters.com',
    'Imane@muntmasters.com',
    'Romayssae@muntmasters.com',
    'Khadija@muntmasters.com',
    'Dina@muntmasters.com',
    'Haytham@muntmasters.com',
    'Ouissame@muntmasters.com',
    'Loubna@muntmasters.com',
    'Miranda@muntmasters.com',
    'Aabir@muntmasters.com',
    'Yannick@muntmasters.com',
    'Aicha@muntmasters.com',
    'Salma@muntmasters.com',
    'Omar@muntmasters.com',
    'Nouhayla@muntmasters.com',
    'Mariam@muntmasters.com',
    'Ikram@muntmasters.com',
    'Oumayma@muntmasters.com',
    'Ouiam@muntmasters.com',
    'Chaida@muntmasters.com',
    'Bilal@muntmasters.com',
    'Hossam@muntmasters.com',
    'Sana@muntmasters.com',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
  ][index];

export const _postTitles = (index: number) =>
  [
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
    'Week 4',
    'Week 5',
    'Week 6',
  ][index];

export const _description = (index: number) =>
  [
    'Autobedrijf Select VOF',
    'Autoservice Midland',
    'Avant Arte B.V.',
    'Bayrak',
    'Balance Bathroom B.V.',
    'Beyuna B.V.',
    'BWR Schoonmaak',
    'Care-4ALL B.V.',
    'Bayaa Holding B.V.',
    'De Future Makers B.V.',
    'Cantera Capital B.V.',
    'De Heus Verbouwingen',
    'CombiCoach B.V.',
    'Barbara Jessica Woesthoff B.V.',
    'Avans Care',
    'Bodie',
    'Basketball Totaal (MI-Stores)',
    'Dak Profijt B.V.',
    'CSP Nederland',
    'Dire Gym B.V.',
    'Bayaa Holding B.V.',
    'De Heus Holding B.V.',
    'Dak Profijt Energie B.V.',
    'Dak Profijt Montage B.V.',
  ][index];

export const _taskNames = (index: number) =>
  [
    `Prepare Monthly Financial Report`,
    `Design New Marketing Campaign`,
    `Analyze Customer Feedback`,
    `Update Website Content`,
    `Conduct Market Research`,
    `Develop Software Application`,
    `Organize Team Meeting`,
    `Create Social Media Posts`,
    `Review Project Plan`,
    `Implement Security Protocols`,
    `Write Technical Documentation`,
    `Test New Product Features`,
    `Manage Client Inquiries`,
    `Train New Employees`,
    `Coordinate Logistics`,
    `Monitor Network Performance`,
    `Develop Training Materials`,
    `Draft Press Release`,
    `Prepare Budget Proposal`,
    `Evaluate Vendor Proposals`,
    `Perform Data Analysis`,
    `Conduct Quality Assurance`,
    `Plan Event Logistics`,
    `Optimize SEO Strategies`,
  ][index];

export const _productNames = (index: number) =>
  [
    'Nike Air Force 1 NDESTRUKT',
    'Nike Space Hippie 04',
    'Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear',
    'Nike Blazer Low 77 Vintage',
    'Nike ZoomX SuperRep Surge',
    'Zoom Freak 2',
    'Nike Air Max Zephyr',
    'Jordan Delta',
    'Air Jordan XXXV PF',
    'Nike Waffle Racer Crater',
    'Kyrie 7 EP Sisterhood',
    'Nike Air Zoom BB NXT',
    'Nike Air Force 1 07 LX',
    'Nike Air Force 1 Shadow SE',
    'Nike Air Zoom Tempo NEXT%',
    'Nike DBreak-Type',
    'Nike Air Max Up',
    'Nike Air Max 270 React ENG',
    'NikeCourt Royale',
    'Nike Air Zoom Pegasus 37 Premium',
    'Nike Air Zoom SuperRep',
    'NikeCourt Royale',
    'Nike React Art3mis',
    'Nike React Infinity Run Flyknit A.I.R. Chaz Bear',
  ][index];
